### ISSUE TITLE
Error when applying llvm patch

### ISSUE THREAD

**Issue by Austin-I** [debjyoti0891/CoVeriS#1]
Hello Debjyoti,
When I follow your instructions in the readme, I encounter an issue when applying the llvm patch (see image below). Did you encounter this issue or do you know a solution for this? Cheers!

<img width="776" alt="image" src="https://github.com/debjyoti0891/CoVeriS/assets/56549006/80e4ed0b-7077-45f5-98f7-e3ed42afad07">

**Comment by debjyoti0891** [comment]
Hi,

Let me check this issue and get back to you, if I can replicate it.


Regards,

Debjyoti

**Comment by debjyoti0891** [comment]
Hi, I just checked with the repository, the patch seems to be working. Can you kindly check if the error persists if you start from a fresh clone of the repository?

<img width="1005" alt="Screenshot 2024-04-24 at 08 50 45" src="https://github.com/debjyoti0891/CoVeriS/assets/5041294/901aa235-840f-4826-b61d-ceed13071fae">

**Comment by Austin-I** [comment]
Hi,
For some reason, this worked although I already tried it twice already before. I got a bit further and am now experiencing a new issue when running the "make -j" command. The output is very large so I will only provide a part of it that is relevant in a text file, it complains that resources are temporarily unavailable. Is this something you are also experiencing?

[resource_unavailable.txt](https://github.com/debjyoti0891/CoVeriS/files/15106031/resource_unavailable.txt)

**Comment by debjyoti0891** [comment]
Hi, I think your system might be failing to spawn new threads. Try something like `make -j 2` to limit usage to two threads and retry. In general, llvm builds take quite significant amount of time.

**Comment by Austin-I** [comment]
Hi, this fixed it, thanks! Managed to get through the rest of the instruction without any problems. What I have noticed is at the end of making spike, there is a warning about path "/lib64" not found so the files are just spat out into the current directory (CoVeriS/riscv-isa-sim/build), just an fyi, I'll assume it is not a problem for now.
<img width="1484" alt="image" src="https://github.com/debjyoti0891/CoVeriS/assets/56549006/776f3fdb-f32c-459c-b1f0-effe443345a1">

Also, slightly unrelated, but Part 1 and Part 2 webpages are not working (Part 3 works fine):
https://debjyoti0891.github.io/compilation/mlir/riscv/2024/03/23/llvm_mlir_1.html
https://debjyoti0891.github.io/compilation/mlir/llvm/riscv/2024/04/09/llvm_mlir_02.html
<img width="853" alt="image" src="https://github.com/debjyoti0891/CoVeriS/assets/56549006/449d7b88-6a6f-4b7d-aef9-5dad5ce8d7b6">

**Comment by debjyoti0891** [comment]
I have fixed the links. I hope the tutorial was useful.

**Comment by Austin-I** [comment]
Hi, tutorial is very useful, thank you! I have another question regarding lowering the example and running it on the SPIKE simulator, I'll open a new issue for this. I consider the current issue as solved so I will close it, thanks again!
