### ISSUE TITLE
Lowering and running example on the SPIKE simulator

### ISSUE THREAD

**Issue by Austin-I** [debjyoti0891/CoVeriS#2]
Hi again, I am attempting to lower and run the benchmark.mlir file in the 'CoVeriS/examples' directory, however there is something blocking me. A guide for lowering and running on the SPIKE simulator was provided by you in Part 1 of the blog, which is made easier using the pattern rules defined in the Makefile in the 'CoVeriS/examples' directory.  

I ran the following commands in the 'CoVeriS/examples' directory and they worked as intended:
`make lower TARGET=benchmark`
`make benchmark_llvm.ll`
`make benchmark_llvm.s`
`make benchmark_llvm.o` note: there's an inconsistency between the pattern rule and command in the blog, in the blog the command outputs benchmark.o, has not impact tho

The following command, `make benchmark_llvm.elf`, does not have the prerequisite patterns, namely "spike_lib.a" and "common/riscv.ld". I assume this is because the 'CoVeriS/examples/common' folder is not present with the correct files, this also blocks `make spike_lib.a` from being ran to create the necessary prerequisite. Where could I find the common folder required? Could you potentially provide it? Thanks in advance!

sidenote: in the Makefile, line number 78 also needs to be edited to point to the correct location of the riscv-gnu-toolchain on your system

**Comment by Austin-I** [comment]
Hi @debjyoti0891, did you have an opportunity to look into this?

**Comment by debjyoti0891** [comment]
I will try to fix the issue this week. Thanks for your patience.

**Comment by debjyoti0891** [comment]
@Austin-I  can you please check if the bug is now resolved?

**Comment by Austin-I** [comment]
Yes it is now resolved, thank you!
